default:
  golem_name: bikeabilitymap
  golem_version: 0.0.0.9000
  app_prod: no
production:
  app_prod: yes
dev:
  golem_wd: /Users/koichiito/Documents/NUS/Academic Matter/2021 Spring/Thesis/bikeabilitymap
